version: "3"

services:
  bitwarden:
    image: bitwardenrs/server:latest
    container_name: bitwarden
    environment:
      - SIGNUPS_ALLOWED=false
      - INVITATIONS_ALLOWED=false
      - ADMIN_TOKEN=longdifficultpasswordhere
      - WEBSOCKET_ENABLED=true
      - SMTP_HOST=smtp.gmail.com
      - SMTP_FROM=user@domain.tld
      - SMTP_PORT=587
      - SMTP_SSL=true
      - SMTP_USERNAME=user@domain.tld
      - SMTP_PASSWORD=applicationpassword
    ports:
      - 8082:80
      - 3012:3012
    volumes:
      - ./data:/data/
    restart: always
