version: "3"

services:
  bitwarden:
    image: bitwardenrs/server:latest
    container_name: bitwarden
    environment:
      - SIGNUPS_ALLOWED=false
    ports:
      - 8082:80
      - 3012:3012
    volumes:
      - ./data:/data/
    restart: always
